# Generated by Django 2.2.24 on 2021-10-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naturebank", "0004_python2_unicode_fixes"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="tempdelete",
            managers=[],
        ),
        migrations.AlterField(
            model_name="biotope",
            name="abandon",
            field=models.ForeignKey(
                blank=True,
                help_text="Επίπεδα εγκατάλειψης οικισμών",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.AbandonmentOption",
                verbose_name="Εγκατάλειψη οικισμών",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Κατηγορία Τόπου",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.BiotopeCategoryOption",
                verbose_name="Κατηγορία Τόπου",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Κατάσταση τόπου",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.ConditionOption",
                verbose_name="Κατάσταση τόπου",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="conservation",
            field=models.ForeignKey(
                blank=True,
                help_text="Επιλογές προτεραιότητας προστασίας",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.ConservationOption",
                verbose_name="Προτεραιότητα προστασίας",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="fire_10",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="fire_1030",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="fire_3050",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="fire_50",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="geo_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Γεωγραφική Ενότητα",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.GeoCodeOption",
                verbose_name="Γεωγραφική Ενότητα",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="knowledge",
            field=models.ForeignKey(
                blank=True,
                help_text="Γνώση για το βιότοπο",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.KnowledgeOption",
                verbose_name="Γνώση",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="reg_wide",
            field=models.ForeignKey(
                blank=True,
                help_text="Ευρύτερη γεωγραφική περιοχή",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.WideArea",
                verbose_name="Ευρύτερη Γεωγραφική Περιοχή",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="social_reaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Επιλογές κοινωνικής αντίδρασης",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.SocialReactionOption",
                verbose_name="Κοινωνική αντίδραση",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_buil",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την δόμηση"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_coll",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την συλλογή"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_cult",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την καλλιέργεια"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_drai",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την αποξήρανση"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_eutr",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από τον ευτροφισμός"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_fish",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την αλιεία"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_fore",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την υλοτομία"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_graz",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την βοσκή"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_hunt",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από το κυνήγι"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_mini",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την εξόρυξη"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_other",
            field=models.BooleanField(
                blank=True, default=False, help_text="Άλλες απειλές/διαταραχές"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_pest",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από τα φυτοφάρμακα"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_poll",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την ρύπανση"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_road",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από την διάνοιξη δρόμων"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="threat_tour",
            field=models.BooleanField(
                blank=True, default=False, help_text="Απειλή από τον τουρισμό"
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="trend",
            field=models.ForeignKey(
                blank=True,
                help_text="Τάση κατάστασης τόπου",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.TrendOption",
                verbose_name="Τάση κατάστασης τόπου",
            ),
        ),
        migrations.AlterField(
            model_name="biotope",
            name="trend_pop",
            field=models.ForeignKey(
                blank=True,
                help_text="Τάση πληθυσμού",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.TrendPopOption",
                verbose_name="Τάση πληθυσμού",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="category_bree",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Είναι αναπαραγόμενο",
                verbose_name="Αναπαραγόμενο",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="category_ende",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Είναι ενδημικό",
                verbose_name="Ενδημικό",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="category_intr",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Είναι εισαχθέν",
                verbose_name="Εισαχθέν",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="category_migr",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Είναι μεταναστευτικό",
                verbose_name="Μεταναστευτικό",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="category_resi",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Κατοικεί μόνιμα",
                verbose_name="Μόνιμος Κάτοικος",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="conservation_bio",
            field=models.ForeignKey(
                blank=True,
                help_text="Κατάσταση διατήρησης του είδους στην Βιόσφαιρα",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_conservation_bio_set",
                to="naturebank.SpeciesConservationOption",
                verbose_name="Βιόσφαιρα",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="conservation_eec",
            field=models.ForeignKey(
                blank=True,
                help_text="Κατάσταση διατήρησης του είδους στην Ευρωπαική Ένωση",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_conservation_eec_set",
                to="naturebank.SpeciesConservationOption",
                verbose_name="Ευρωπαϊκή Ένωση",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="conservation_gr",
            field=models.ForeignKey(
                blank=True,
                help_text="Κατάσταση διατήρησης του είδους στην Ελλάδα",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_conservation_gr_set",
                to="naturebank.SpeciesConservationOption",
                verbose_name="Ελλάδα",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="conservation_prio",
            field=models.ForeignKey(
                blank=True,
                help_text="Προτεραιότητα προστασίας",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.SpeciesConservationPriorityOption",
                verbose_name="Προτεραιότητα Προστασίας",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="exploit_coll",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Εκμετάλλευση από τη σύλλογη",
                verbose_name="Συλλογή",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="exploit_fish",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Εκμετάλλευση από το αλιεία",
                verbose_name="Αλιεία",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="exploit_graz",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Εκμετάλλευση από τη βοσκή",
                verbose_name="Βοσκή",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="exploit_hunt",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Εκμετάλλευση από το κυνήγι",
                verbose_name="Κυνήγι",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="exploit_logg",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Εκμετάλλευση από την υλοτομία",
                verbose_name="Υλοτομία",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="knowledge",
            field=models.ForeignKey(
                blank=True,
                help_text="Το επίπεδο γνώσης στο συγκεκριμένο είδος",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.SpeciesKnowledgeOption",
                verbose_name="Γνώση",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="plant_kind",
            field=models.ForeignKey(
                blank=True,
                help_text="Υποκατηγορία για φυτό (Αν δεν είναι φυτό πρέπει να αφεθεί κενό)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.SpeciesPlantKindOption",
                verbose_name="Κατηγορία Φυτού",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="protection",
            field=models.ForeignKey(
                blank=True,
                help_text="Επίπεδο προστασίας του είδους",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.SpeciesProtectionOption",
                verbose_name="Προστασία",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="rarity_bio",
            field=models.ForeignKey(
                blank=True,
                help_text="Σπανιότητα του είδους στην Βιόσφαιρα",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_rarity_bio_set",
                to="naturebank.SpeciesRarityOption",
                verbose_name="Βιόσφαιρα",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="rarity_eec",
            field=models.ForeignKey(
                blank=True,
                help_text="Σπανιότητα του είδους στην Ευρωπαική Ένωση",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_rarity_eec_set",
                to="naturebank.SpeciesRarityOption",
                verbose_name="Ευρωπαϊκή Ένωση",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="rarity_gr",
            field=models.ForeignKey(
                blank=True,
                help_text="Σπανιότητα του είδους στην Ελλάδα",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_rarity_gr_set",
                to="naturebank.SpeciesRarityOption",
                verbose_name="Ελλάδα",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="species_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Κατηγορία χλωρίδας/πανίδας που ανήκει το είδος.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.SpeciesCategoryOption",
                verbose_name="Κατηγορία Είδους",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_buil",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την δόμηση",
                verbose_name="Δόμηση",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_coll",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την συλλογή",
                verbose_name="Συλλογή",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_cult",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την καλλιέργεια",
                verbose_name="Καλλιέργεια",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_drai",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την αποξήρανση",
                verbose_name="Αποξήρανση",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_eutr",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από τον ευτροφισμό",
                verbose_name="Ευτροφισμός",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_fish",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την αλιεία",
                verbose_name="Αλιεία",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_fore",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την υλοτομία",
                verbose_name="Υλοτομία",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_graz",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την βοσκή",
                verbose_name="Βοσκή",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_hunt",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από το κυνήγι",
                verbose_name="Κυνήγι",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_other",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Άλλες απειλές",
                verbose_name="Άλλες Απειλές",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_pest",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από τα φυτοφάρμακα",
                verbose_name="Φυτοφάρμακα",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_poll",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την ρύπανση",
                verbose_name="Ρύπανση",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_road",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από την διάνοιξη δρόμων",
                verbose_name="Διάνοιξη Δρόμων",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="threat_tour",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Απειλή από τον τουρισμό",
                verbose_name="Τουρισμός",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="trend",
            field=models.ForeignKey(
                blank=True,
                help_text="Ο ρυθμός ανάπτυξης του είδους",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="naturebank.SpeciesTrendOption",
                verbose_name="Τάση",
            ),
        ),
    ]
